customhost = "database-1.c1efdodxxtlq.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "harchunwai-employee"
customregion = "us-east-1"